### PR TITLE
Set +x attribute for executables.

### PR DESCRIPTION
**Pull request by pravic**
I hope, it will not be reset after the next build.

Essentially, this PR adds executable attributes for all Linux / OSX binaries, it will allow not to do that manually after each SDK update (and then revert it back to allow git pull).

It was done by `git update-index --chmod=+x packfolder tiscript ...`.

### CODE REVIEW

**Comment by pravic** [comment]
No, it won't.

**Comment by pravic** [comment]
Andrew, are here any objectives? Because this is a safe but helpful change.

**Comment by c-smile** [comment]
I think that it is better to provide batch file that will apply chmod -x for that, no? 
Not sure but I suspect that -x attribute will be dropped each time when I will update these exe.

**Comment by pravic** [comment]
No, I've checked that, even on Windows. Git sustains attributes after building / overwriting executables.

That's why a batch/sh script is not needed, yet it requires to be run every time and to be reset before a git pull with the next release.

**Pull request merged**
